import type { Tool, ToolListResponse } from "@/types/tool";

const now = new Date().toISOString();

const seller = {
  id: "local-curated-seller",
  display_name: "Hackmarket Curated",
  avatar_url: null,
  username: "hackmarket_curated",
};

export const LOCAL_FALLBACK_TOOLS: Tool[] = [
  {
    id: "local-stormcast-fcn3-forecast",
    seller_id: seller.id,
    seller,
    name: "StormCast FCN3 Forecast API",
    slug: "stormcast-fcn3-forecast",
    tagline:
      "Run FCN3-style weather forecasts with localized storm windows, risk summaries, and hazard alerts.",
    description:
      "Generate localized forecast windows, storm-zone detection, ensemble spread, and operational recommendations inspired by the Treehacks Earth2Studio service.",
    category: "data_analysis",
    status: "live",
    ownership_type: "royalty",
    input_type: "json",
    output_type: "json",
    input_schema: {
      example_input: {
        location_name: "San Francisco, CA",
        lat: 37.7749,
        lon: -122.4194,
        start_time: "2026-05-16T00:00:00Z",
        steps: 48,
        ensemble_members: 8,
      },
    },
    output_schema: {
      example_output: {
        success: true,
        tool: "stormcast-fcn3-forecast",
        risk_summary: {
          peak_risk: "high",
          storm_zone_count: 2,
        },
      },
    },
    price_per_request: "0.020000",
    one_time_price: null,
    demo_url: null,
    api_endpoint: "http://localhost:3040/forecast-fcn3",
    docker_image_uri: null,
    github_url: "https://github.com/alangrewco/treehacks",
    source_s3_key: null,
    config_s3_key: null,
    entry_command: "node server.js",
    port: 3040,
    processing_error: null,
    documentation:
      "POST /forecast-fcn3 with { location_name?, lat?, lon?, start_time?, steps?, ensemble_members? }",
    avg_response_time_ms: 540,
    total_requests: 58,
    uptime_percentage: "99.40",
    is_featured: true,
    view_count: 118,
    created_at: now,
    updated_at: now,
  },
  {
    id: "local-personaplex-voice-agent",
    seller_id: seller.id,
    seller,
    name: "PersonaPlex Voice Agent",
    slug: "personaplex-voice-agent",
    tagline:
      "Turn live-call transcripts into intent, urgency, next actions, and follow-up drafts.",
    description:
      "Analyze support-call transcripts and return structured routing decisions, urgency, extracted entities, and a suggested follow-up inspired by the Treehacks PersonaPlex demo.",
    category: "nlp",
    status: "live",
    ownership_type: "royalty",
    input_type: "json",
    output_type: "json",
    input_schema: {
      example_input: {
        transcript:
          "Hi, this is Alex from account 44821. Our pickup was missed again and I need someone to reschedule it for tomorrow morning.",
        customer: {
          name: "Alex Rivera",
          account_id: "44821",
        },
        context: {
          business_name: "Civic Utility Services",
        },
      },
    },
    output_schema: {
      example_output: {
        success: true,
        tool: "personaplex-voice-agent",
        primary_intent: "missed_service",
        urgency: "high",
        sentiment: "frustrated",
      },
    },
    price_per_request: "0.012000",
    one_time_price: null,
    demo_url: null,
    api_endpoint: "http://localhost:3050/analyze-call",
    docker_image_uri: null,
    github_url: "https://github.com/alangrewco/treehacks",
    source_s3_key: null,
    config_s3_key: null,
    entry_command: "node server.js",
    port: 3050,
    processing_error: null,
    documentation:
      "POST /analyze-call with { transcript, customer?, context? }",
    avg_response_time_ms: 190,
    total_requests: 73,
    uptime_percentage: "99.55",
    is_featured: true,
    view_count: 134,
    created_at: now,
    updated_at: now,
  },
  {
    id: "local-iris-candidate-ranker",
    seller_id: seller.id,
    seller,
    name: "Iris Candidate Ranker",
    slug: "iris-candidate-ranker",
    tagline:
      "Rank applicants with fit scores, skill evidence, recruiter criteria, and resume flags.",
    description:
      "Score candidate resumes against a job description and recruiter prompt, then return a ranked shortlist with reasoning.",
    category: "automation",
    status: "live",
    ownership_type: "royalty",
    input_type: "json",
    output_type: "json",
    input_schema: {
      example_input: {
        job: {
          title: "Founding Frontend Engineer",
          description:
            "Build React and TypeScript product surfaces for a fast-moving AI startup.",
          skills: ["React", "TypeScript", "Next.js", "Product thinking"],
        },
        prompt: "Prioritize startup ownership, React, TypeScript, and product sense.",
        candidates: [
          {
            id: "cand_001",
            name: "Ava Chen",
            resume_text:
              "Frontend engineer with React, TypeScript, Next.js, design systems, and founding team experience.",
            skills: ["React", "TypeScript", "Next.js"],
          },
          {
            id: "cand_002",
            name: "Marco Silva",
            resume_text: "Backend engineer focused on Python, Django, Postgres, and AWS.",
            skills: ["Python", "Django", "Postgres"],
          },
        ],
        limit: 2,
      },
    },
    output_schema: {
      example_output: {
        success: true,
        tool: "iris-candidate-ranker",
        ranked: [
          {
            candidate_id: "cand_001",
            name: "Ava Chen",
            score: 92,
            confidence: 0.91,
            recommendation: "strong_yes",
          },
        ],
      },
    },
    price_per_request: "0.015000",
    one_time_price: null,
    demo_url: null,
    api_endpoint: "http://localhost:3030/rank",
    docker_image_uri: null,
    github_url: "https://github.com/pahu2353/HireUp",
    source_s3_key: null,
    config_s3_key: null,
    entry_command: "node server.js",
    port: 3030,
    processing_error: null,
    documentation: "POST /rank with { job, candidates, prompt?, limit? }",
    avg_response_time_ms: 310,
    total_requests: 64,
    uptime_percentage: "99.60",
    is_featured: true,
    view_count: 145,
    created_at: now,
    updated_at: now,
  },
  {
    id: "local-mirage-scene-reconstructor",
    seller_id: seller.id,
    seller,
    name: "Mirage Scene Reconstructor",
    slug: "mirage-scene-reconstructor",
    tagline:
      "Turn uploaded photos or a short video clip into a 3D scene package for robotics demos.",
    description:
      "Convert reference imagery into a synthetic 3D scene summary inspired by Mirage's reconstruction pipeline.",
    category: "generation",
    status: "live",
    ownership_type: "royalty",
    input_type: "json",
    output_type: "json",
    input_schema: {
      example_input: {
        prompt: "road blocked by a fallen tree after a storm",
        category: "autonomous",
      },
      fields: [
        { name: "prompt", type: "string", required: false, placeholder: "Describe the scene" },
        { name: "category", type: "string", required: false, placeholder: "autonomous" },
        { name: "images", type: "file", required: false, placeholder: "Upload reference images" },
        { name: "video", type: "file", required: false, placeholder: "Upload a short video clip" },
      ],
    },
    output_schema: {
      example_output: {
        scene_id: "mirage_ab12cd34",
        mode: "image_reconstruction",
        category: "autonomous",
      },
    },
    price_per_request: "0.025000",
    one_time_price: null,
    demo_url: null,
    api_endpoint: "http://localhost:3020/reconstruct",
    docker_image_uri: null,
    github_url: "https://github.com/kyan-yang/Mirage",
    source_s3_key: null,
    config_s3_key: null,
    entry_command: "node server.js",
    port: 3020,
    processing_error: null,
    documentation: "POST /reconstruct with { prompt?, category?, images?, video? }",
    avg_response_time_ms: 880,
    total_requests: 41,
    uptime_percentage: "99.50",
    is_featured: true,
    view_count: 97,
    created_at: now,
    updated_at: now,
  },
  {
    id: "local-email-intent-router",
    seller_id: seller.id,
    seller,
    name: "Email Intent Router",
    slug: "email-intent-router",
    tagline: "Classify inbound emails into support, sales, billing, or spam.",
    description:
      "Route inbound email text into actionable intent categories with confidence scores.",
    category: "automation",
    status: "live",
    ownership_type: "royalty",
    input_type: "json",
    output_type: "json",
    input_schema: {
      example_input: { email: "urgent refund for double charge" },
    },
    output_schema: {
      example_output: { category: "billing", confidence: 0.91 },
    },
    price_per_request: "0.003000",
    one_time_price: null,
    demo_url: null,
    api_endpoint: "http://localhost:3010/classify",
    docker_image_uri: null,
    github_url: "https://github.com/sammcheng/start",
    source_s3_key: null,
    config_s3_key: null,
    entry_command: "node server.js",
    port: 3010,
    processing_error: null,
    documentation: "POST /classify with { email, categories? }",
    avg_response_time_ms: 95,
    total_requests: 182,
    uptime_percentage: "99.80",
    is_featured: true,
    view_count: 220,
    created_at: now,
    updated_at: now,
  },
  {
    id: "local-home-accessibility-checker",
    seller_id: seller.id,
    seller,
    name: "Home Accessibility Checker",
    slug: "home-accessibility-checker",
    tagline:
      "Analyze listing links or photos for accessibility barriers and recommendations.",
    description:
      "Detect common accessibility issues from listing photos and return an accessibility score.",
    category: "computer_vision",
    status: "live",
    ownership_type: "royalty",
    input_type: "json",
    output_type: "json",
    input_schema: null,
    output_schema: null,
    price_per_request: "0.050000",
    one_time_price: null,
    demo_url: null,
    api_endpoint: "https://home-accessibility-checker.onrender.com",
    docker_image_uri: null,
    github_url: "https://github.com/sammcheng/start",
    source_s3_key: null,
    config_s3_key: null,
    entry_command: "node server.js",
    port: 3000,
    processing_error: null,
    documentation: "Use URL or uploaded images.",
    avg_response_time_ms: 420,
    total_requests: 74,
    uptime_percentage: "99.90",
    is_featured: true,
    view_count: 130,
    created_at: now,
    updated_at: now,
  },
];

export function buildLocalToolList(limit = 20): ToolListResponse {
  const items = LOCAL_FALLBACK_TOOLS.slice(0, limit);
  return {
    items,
    total: items.length,
    page: 1,
    limit,
    pages: 1,
  };
}
